# =============================================================================
# Helix OS - Codecov Configuration
# =============================================================================
# Code coverage reporting configuration
# https://docs.codecov.com/docs/codecovyml-reference
# =============================================================================

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: false
        only_pulls: false

    patch:
      default:
        target: 80%
        threshold: 10%
        informational: false
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "target/**/*"
  - "build/**/*"
  - "**/*.md"
  - "**/tests/**/*"
  - "**/benches/**/*"
  - "boot/src/*.asm"

flags:
  kernel:
    paths:
      - core/
      - hal/
      - subsystems/
    carryforward: true

  modules:
    paths:
      - modules/
      - modules_impl/
    carryforward: true

  filesystem:
    paths:
      - fs/
    carryforward: true
